name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install
        run: yarn install

      - name: ESLint
        run: yarn run lint

      - name: Prettier
        run: yarn prettier --write .

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Compile
        run: yarn run build

      - name: "Build package"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: built
          filename: "monitor-info-grabber-${{ steps.vars.outputs.sha_short }}.xpi"

      - run: ls built

      - name: "Publish Firefox Extension"
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: ${{ secrets.FIREFOX_EXTENSION_UUID }}
          xpi-path: ${{ steps.web-ext-build.outputs.target }}
          self-hosted: false
          jwt-issuer: ${{ secrets.FIREFOX_API_KEY }}
          jwt-secret: ${{ secrets.FIREFOX_API_SECRET }}
